### ISSUE TITLE
apk stuck fetching alpine's repo index

### ISSUE THREAD

**Issue by n3wborn** [nystudio107/vitejs-docker-dev#1]
### Describe the bug
apk stays stuck when I `make docker`

### To reproduce
Steps to reproduce the behaviour:
1. `git clone https://github.com/nystudio107/vitejs-docker-dev.git`
2. `cd vitejs-docker-dev`
3. `make docker`
4. See apk stuck trying to fetch alpine's repo index

### Expected behaviour
As explained in README, this command should install git and download vitejs repo, and then the rest.

### Screenshots
![image](https://user-images.githubusercontent.com/10246722/147424329-7de99f7e-a102-4055-8f91-65d65e56b399.png)

### Versions
Fedora 32 - linux 5.11.22-100.fc32.x86_64
Docker version 20.10.7, build f0df350

**Comment by n3wborn** [comment]
Using multistage build using "https://github.com/alpine-docker/git" to install vitejs repo could potentially avoid this kind of issue

**Comment by khalwat** [comment]
This has to be a transient or localized issue of some sort, preventing access to the CDN. I just did your steps to reproduce, and it worked fine here.

If it's hung on `apk add --nocache git` that just means the package manager got hung up somehow, likely due to a network issue.

Please give it a try again, and let me know if you have further issues.
